### ISSUE TITLE
[Feature Request] Add item tags

### ISSUE THREAD

**Issue by LootDust** [Type-32/PreciseManufacturing#13]
Items in this mod now do not have any item tags, which is inconvenient for modpack makers to add items into loot_tables or recipes with KubeJS or CraftTweaker.
这个模组的物品现在没有任何物品标签，这对于整合包作者而言很不方便，尤其是在用KJS或者CrT来批量给这些物品加入战利品表或者配方中的时候。

**Describe the solution you'd like**
Add tags for every type of items such as #gun_part_blueprint or something else.
希望能给每种物品加上标签，比如给枪械部件蓝图加上#gun_part_blueprint之类的标签。

**Comment by Type-32** [comment]
Added tags `prma:molten_copper_fluids`, `prma:molten_iron_fluids`, `prma:molten_brass_fluids` for better extensibility
我在V0.2.6添加了我上面列出来的三个流体标签

And also item tags `prma:ammo_blueprints`, `prma:ammo_casing_components`, `prma:ammo_casts`, `prma:ammo_head_components`, `prma:components`, `prma:materials`, `prma:weapon_blueprints`, `prma:weapon_casts`, `prma:weapon_components`
也添加了我上面列出来的一堆我不想复制黏贴的物品标签

You can now add more fluids from the other mods you want into these three corresponding tags now and it'll work in the recipes
You can also use these item tags wherever you want for you own customizations
现在你能随便往流体标签里面加其他模组的流体和使用新的物品标签用在你的模组包里面

Also working on KubeJS compat, stay tuned for V0.2.6 QoL
我现在正在弄KubeJS的兼容，敬请期待
