### ISSUE TITLE
[Bug] 这个模组无法在1.18.2服务端加载

### ISSUE THREAD

**Issue by RuobaiCN** [Type-32/PreciseManufacturing#17]
如题，1.18.2的forge 21版本和18版本均会报错其他版本没测试。原因不明
模组只有他自己以及 机械动力本体和tacz。

日志:
[latest (1).txt](https://github.com/user-attachments/files/16115409/latest.1.txt)

**Comment by Type-32** [comment]
去下载0.2.5-alpha-hotfix1

**Comment by RuobaiCN** [comment]
okk
