### ISSUE TITLE
[Feature Request] Compatibility for Other Mods' Molten Metal Fluids

### ISSUE THREAD

**Issue by ripoy** [Type-32/PreciseManufacturing#7]
add forge tag for recipes with molten brass and copper, i just wanna use molten metals from other create addons. please.
all mods for metallurgy using super heat for molt metals, so u need automate blaze cakes

**Comment by Type-32** [comment]
You should open a new feature request if you want blaze cakes automated, though automating blaze cakes would potentially violate Create's gameplay design

**Comment by Type-32** [comment]
This is a kinda hard request to do because of how the registration of fluids works and how the recipes were registered. Though I would appreciate if you can write out some of the fluid IDs you mentioned that are in other mods.

For me to implement this, I would need to categorize fluids under three tags:
prma:molten_copper_fluids
prma:molten_brass_fluids
prma:molten_iron_fluids

I'd appreciate if you can categorize them into these three tags

**Comment by ripoy** [comment]
ill try it, but not shure bc i dont know modding well

**Comment by Type-32** [comment]
just write out the fluids you would think that can go under those tags, no need to mod or anything

**Comment by ripoy** [comment]
also i didnt mean U need to create new recept for blaze cackes, i mean me or some1 gotta automate them instead automate ur molten metals recipes, if some1 has another molten metal in his storage or smth, bc how i sayd, i need superheated basin for melting

**Comment by ripoy** [comment]
![image](https://github.com/Type-32/PreciseManufacturing/assets/117046926/01f5a7af-8f41-4ec2-8800-7af0e2692294)
like this, add forge tag for copper and brass
for example 

#forge:molten_copper

and ofc u need to change recipes with fluids, use tag instead name
i think its gotta work

**Comment by Type-32** [comment]
what mods were you using that you want the fluids in them to be added in?

**Comment by ripoy** [comment]
wym? where i got some molten metals?

**Comment by ripoy** [comment]
big cannons, metallurgy, molten metals, the factory must grow

**Comment by Type-32** [comment]
right, I'll look into them now, thanks

**Comment by ripoy** [comment]
mb like that should work

#forge:molten_iron

#forge:molten_copper

#forge:molten_brass

**Comment by ripoy** [comment]
np, just wanna play good mods)

**Comment by Type-32** [comment]
Added tags `prma:molten_copper_fluids`, `prma:molten_iron_fluids`, `prma:molten_brass_fluids` for better extensibility

You can now add more fluids from the other mods you want into these three corresponding tags now and it'll work in the recipes

Also working on KubeJS compat, stay tuned
