### ISSUE TITLE
missing names and textures (prma-1.20.1-0.2.3-alpha-5db4b282-all)

### ISSUE THREAD

**Issue by ripoy** [Type-32/PreciseManufacturing#8]
![image](https://github.com/Type-32/PreciseManufacturing/assets/117046926/0cbfb8ce-fd55-4979-a4d1-f4021d16518b)
![image](https://github.com/Type-32/PreciseManufacturing/assets/117046926/c688eb0a-2f98-4311-836f-4c6c9266d852)
![image](https://github.com/Type-32/PreciseManufacturing/assets/117046926/5f7a975e-c8a1-443f-ae24-6e48b84c30d4)
![image](https://github.com/Type-32/PreciseManufacturing/assets/117046926/dff9b35f-64df-4ee3-8249-06c8c27223f1)
![image](https://github.com/Type-32/PreciseManufacturing/assets/117046926/adafdf46-0a1c-4226-b44b-860f34f0c4be)

**Comment by Type-32** [comment]
I missed a few translations, my b

**Comment by Type-32** [comment]
Fixed in 0.2.4

**Comment by Ripoy** [comment]
nah texture still doesnt work properly

**Comment by ripoy** [comment]
![2024-06-10_19 41 22](https://github.com/Type-32/PreciseManufacturing/assets/117046926/dbef454e-e6e9-491e-8d08-8b0a3231c064)
gotta look like this?

**Comment by Type-32** [comment]
as of the current moment, yes
